# Generated by Django 2.0.5 on 2018-05-15 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='CategoryPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'category_price',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('duration', models.TimeField(blank=True, null=True)),
                ('trailer', models.CharField(blank=True, max_length=255, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('poster', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'film',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('seats_map', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hall',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=45)),
                ('visitor_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=45)),
                ('locking_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.CharField(max_length=45)),
                ('number', models.CharField(max_length=45)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Hall')),
            ],
            options={
                'db_table': 'seat',
            },
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'seat_category',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('format', models.CharField(blank=True, max_length=45, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Film')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Hall')),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.SeatCategory'),
        ),
        migrations.AddField(
            model_name='order',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Seat'),
        ),
        migrations.AddField(
            model_name='order',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Session'),
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Genre'),
        ),
        migrations.AddField(
            model_name='film',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='language_id', to='orders.Language'),
        ),
        migrations.AddField(
            model_name='film',
            name='subtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subtitle_id', to='orders.Language'),
        ),
        migrations.AddField(
            model_name='categoryprice',
            name='seat_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seat_category_id', to='orders.SeatCategory'),
        ),
        migrations.AddField(
            model_name='categoryprice',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_id', to='orders.Session'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryprice',
            unique_together={('seat_category', 'session')},
        ),
    ]
