# Generated by Django 2.0.5 on 2018-05-16 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180516_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='language_id', to='orders.Language'),
        ),
        migrations.AlterField(
            model_name='film',
            name='subtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subtitle_id', to='orders.Language'),
        ),
    ]
