# Generated by Django 2.0.4 on 2018-05-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
